# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Помидор",
  "description": "Лучшие помидоры на рынке"
}

###

# получение продуктов
GET {{baseUrl}}/products/4

###

# обновление продукта
PATCH {{baseUrl}}/products/2/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/2/

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=помид

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "name": "Центральный",
  "address": "мой адрес не дом и не улица, мой адрес Советский Союз: www.ленинград-спб.ru3",
  "positions": [
    {
      "product": 2,
      "quantity": 250,
      "price": 120.50
    },
    {
      "product": 3,
      "quantity": 100,
      "price": 180
    }
  ]
}

###

# обновление товаров на складе
PATCH {{baseUrl}}/stocks/Центральный/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 250,
      "price": 120.50
    },
    {
      "product": 3,
      "quantity": 100,
      "price": 180
    }
  ]
}

###

# обновление товаров на складе
PATCH {{baseUrl}}/stocks/У лукоморья/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 100,
      "price": 130.80
    },
    {
      "product": 3,
      "quantity": 243,
      "price": 145
    }
  ]
}

###

# поиск складов, где есть определённый продукт
GET {{baseUrl}}/stocks/?product=4

###

# поиск склада по его названию
GET {{baseUrl}}/stocks/У лукоморья

###

# удаление склада (по его названию)
DELETE {{baseUrl}}/stocks/Октябрьский/

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "name": "Октябрьский",
  "address": "ул. Пролетарская, 23",
  "positions": [
    {
      "product": 2,
      "quantity": 150,
      "price": 150
    },
    {
      "product": 3,
      "quantity": 170,
      "price": 170
    }
  ]
}

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "name": "У лукоморья",
  "address": "На деревне у дедушки",
  "positions": [
    {
      "product": 4,
      "quantity": 210,
      "price": 160
    },
    {
      "product": 3,
      "quantity": 170,
      "price": 200
    }
  ]
}

###

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Огурец",
  "description": "Самые зелёные огурцы во вселенной"
}

###

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Баклажан",
  "description": "Не постать никаким помидорам и огурцам"
}
